language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
before_install:
  - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
      fi
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -q '.ino' || {
        echo "Sources unchanged. Skip build."
        exit
      }
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
  - build_platform uno
  - build_platform leonardo
  - build_platform mega2560